openapi: 3.0.1
info: 
    title: Unahur antisocial API
    version: 1.0.0
    description: API backend de la red social anti-social
servers:
  - url: http://localhost:3000
tags:
  - name: post
    description: Este endpoint maneja toda la información relacionada con los Posts.
  
  - name: user
    description: Este endpoint maneja toda la información relacionada con los usuarios
  
  - name: comment
    description: Este endpoint maneja toda la información relacionada con los comentarios
  
  - name: tag
    description: Este endpoint maneja toda la información relacionada con los tags
paths:
  /post:
    get:
      tags:
      - post 
      summary: Obtiene a todos los posts
      responses:
        '200':
          description: Devuelve todos los posts
        '404':
          description: Posts no encontrados
    post:
      tags:
      - post
      summary: Crea nuevas publicaciones
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/BodyPostPublicacion'
      responses:
        '201':
            description: Publicación creada

  /post/{id}:

    get:
      tags:
      - post
      summary: Busca un post por un ID especifico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
           
    put:
      tags:
      - post
      summary: Actualiza la información de una publicación
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyPostPublicacion'
      responses:
        '200':
          description: Publicación actualizada con éxito
    
    delete:
      tags:
      - post
      summary: Elimina un post mediante un ID especifico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  
  /user:
    get:
      tags:
      - user
      summary: Obtiene todos los usuarios
      responses:
        '200':
          description: Usuarios obtenidos
      
    post:
      tags:
      - user
      summary: Crea nuevos usuarios
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/BodyUserSchema'
      responses:
        '201':
            description: Usuario creado

  /user/{id}:

    get:
      tags:
      - user
      summary: Busca un usuario por un ID especifico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
           
    put:
      tags:
      - user
      summary: Actualiza la información de un usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyUserSchema'
      responses:
        '200':
          description: Usuario actualizado con éxito

    delete:
      tags:
      - user
      summary: Elimina un usuario mediante su ID.
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado
    
    
  
  /user/{nickname}:
    get:
      tags:
      - user
      summary: Busca un usuario por nickname.
      parameters:
        - name: nickname
          in: path
          required: true
          schema:
            type: string
    

  /comment:
    get:
      tags:
      - comment
      summary: Obtiene todos los comentarios
      response:
        '200':
          description: Comentarios obtenidos

    post:
      tags:
      - comment
      summary: Crea nuevos comentarios
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/CommentSchema'
      responses:
        '201':
            description: Comentario creado
          
  /comment/{id}:
    get:
      tags:
      - comment
      summary: Busca un comentario por un ID especifico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: comentario encontrado
           
    put:
      tags:
      - comment
      summary: Actualiza la información de un comentario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentSchema'
      responses:
        '200':
          description: Usuario actualizado con éxito

    delete:
      tags:
      - comment
      summary: Elimina un comentario mediante su ID.
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: comentario eliminado
    
  /tag:
    get:
      tags:
      - tag
      summary: Obtiene todos los tags
      response:
        '200':
          description: tags obtenidos

    post:
      tags:
      - tag
      summary: Crea nuevos tags
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/TagSchema'
      responses:
        '201':
            description: tag creado
          
  /tag/{id}:
    get:
      tags:
      - tag
      summary: Busca un tag por un ID especifico.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: tag encontrado
           
    put:
      tags:
      - tag
      summary: Actualiza la información de un tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagSchema'
      responses:
        '200':
          description: Tag actualizado con éxito

    delete:
      tags:
      - tag
      summary: Elimina un tag mediante su ID.
      parameters:
        - name: ID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: tag eliminado
      
        

components:
  responses:
  
  parameters:
  
  schemas:
     BodyPostPublicacion:
        type: object
        properties: 
          nickname:
            type:
              string
            description: nickname del usuario que va a crear una publicación
          contenido:
            type:
              string
            description: Contenido que va a tener la publicación
          tags:
            type:
              string
            description: El id del tag que va a estar asociado a la publicación.

     BodyUserSchema:
        type: object
        properties:
          nickname:
            type: string
            description: El nickname del Usuario
          followers:
            type: string
            description: Los seguidores del usuario
     CommentSchema:
      type: object
      properties:
        contenido:
          type: string
          description: El contenido del comentario
        user:
          type: string
          description: El id del usuario que realizó el comentario
        post:
          type: string
          description: El id del post al que pertenece el comentario

     TagSchema:
      type: object
      properties:
        nombre:
          type: string
          description: El nombre que va a tener el tag  
           